### ISSUE TITLE
关于跨平台

### ISSUE THREAD

**Issue by AoEiuV020** [AWarmHug/widget_screenshot#2]
我看不跨平台的仅仅是截图“合并”的部分，
这部分无法纯flutter/dart实现吗？有什么坑或者有什么方案以什么原因失败了可以说出来讨论一下，
我想还是应该尽量做到纯flutter跨平台实现，
毕竟只是图片拼接应该总有办法的吧，

**Comment by AoEiuV020** [comment]
自己实现了，
https://github.com/AoEiuV020/widget_screenshot

**Comment by AWarmHug** [comment]
> 我看不跨平台的仅仅是截图“合并”的部分， 这部分无法纯flutter/dart实现吗？有什么坑或者有什么方案以什么原因失败了可以说出来讨论一下， 我想还是应该尽量做到纯flutter跨平台实现， 毕竟只是图片拼接应该总有办法的吧，

在之前，我尝试使用[image](https://pub.dev/packages/image)合并图片过，比原生要慢很多，所以打算，在Android和iOS上原生合并，其他平台上使用这个库合并图片

**Comment by AoEiuV020** [comment]
@AWarmHug 是的我现在就是用image处理的，
貌似没有方便的api用来合并，只能是创建一个大图片然后逐个像素点复制，纯cpu计算没有硬件加速确实慢，
但我不打算解决慢的问题，打算之后加个异步处理让用户等着就是了，
