### ISSUE TITLE
长截图可能没有截全

### ISSUE THREAD

**Issue by AoEiuV020** [AWarmHug/widget_screenshot#4]
就项目内的example，100个数据的列表截图，我这边大概只能截到63，然后就停止滚动了，
和手机性能有关吗？感觉是等待时间和滚动动画的冲突，
![image](https://github.com/AWarmHug/widget_screenshot/assets/11682198/cb285aa8-5866-4067-a7d4-ba9848641faf)

**Comment by AoEiuV020** [comment]
自己实现了，
https://github.com/AoEiuV020/widget_screenshot

**Comment by AWarmHug** [comment]
> 就项目内的example，100个数据的列表截图，我这边大概只能截到63，然后就停止滚动了， 和手机性能有关吗？感觉是等待时间和滚动动画的冲突， ![image](https://private-user-images.githubusercontent.com/11682198/283759444-cb285aa8-5866-4067-a7d4-ba9848641faf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjg0ODEsIm5iZiI6MTcxMzI2ODE4MSwicGF0aCI6Ii8xMTY4MjE5OC8yODM3NTk0NDQtY2IyODVhYTgtNTg2Ni00MDY3LWE3ZDQtYmE5ODQ4NjQxZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDExNDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZTg1ZjQ5NzkzZjJlMzJhZmViMWUzMWYwM2E2ODdlZmIxOGJkOTc4OWUwZmRiYzAwYmFjYWMzNWFhNjU1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KHpdpz88nkOnGMsImzGXFhXhkTkYQYbS9qIufuI-NBw)

有默认的最大长度
